### PR TITLE
ztrot's initial art upload

### PR DESCRIPTION
**Pull request by ztrot**
initial upload

### CODE REVIEW

**Comment by peppy** [comment]
why is the plate disconnected in the default state?

**Comment by ztrot** [comment]
Ask daru, when he adjusted the changes he sent it back like that, I'll reattach it and make sure it is properly centered.

**Comment by peppy** [comment]
rbrat already did it, like 2 days ago >.>

**Comment by ztrot** [comment]
oh, never mind then.

On Tue, May 27, 2014 at 5:23 PM, Dean Herbert notifications@github.comwrote:

> rbrat already did it, like 2 days ago >.>
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ppy/osu-artwork/pull/1#issuecomment-44343365
> .

## 

Justin "ztrot" Mayfield
osu! Media Development
Academy Creator

**Pull request merged**
